---
language: python
addons:
  sonarcloud:
    organization: "slavaklevleev" # the key of the org you chose at step #3
    token:
      secure: "9a508e466c4954e8820d8b205132a0ae94ceb143" # encrypted value of your token
script:
  - pytest
  - sonar-scanner