language: python
addons:
  sonarcloud:
    organization: slavaklevleev
    token:
      secure: "a6EVhIPHlYgyXYDHR2W9M/wHr6VN7ZbO3R5oxQbcJq+nq5cMCl2YeRUxSV3I2lfyIbyrpgsedlS/W3hWyEi4DdhqJHO0gLKQn2KVHJiBYQtQjtjTz7kwEPVfnSxUyZd6g6wnLOyi+IjBujs1BtTb7vgBlZ0PLVso+aDRP5fG76+AflDD1yt7N9LUFTNBdqq/N+YV3W3AEfz6Y/4e7Rfsgsl6NAaXcjPKPK7N/BixiQoeCFvOYVyfPARkpe2CQuW9MptYZSWmXvnqI3FDzaHrZOvJ97nLenoDfeT914HDUIDTGBbY4elEvNl2U9rlUNIJHPhD4zSQmp7NiREwCRn0vKSeUMQAxDI0aPalSiOTluMTyCQwootU6ibcjcQx4SDV+bVaKgaBmtBsbn7YU5BsiRyTB+zkpviMHARbeP3vywWYvwgOz9KdRiUr8qkPSx87exwvuN2ADgc5kqfkV1ETEfRAqRittGbd1FCpqopAZUUR/0DFuQL55bD9ENKgxkgySt0dj417tTuWtD8XU2xZDIeWJQwVDQHmTVR9STTyLojggDubiUsq/Owf8uX7j5bCu+vWRLZ1MeXrxPC2xWUd98bxxbGKMcFEJopSyNGi4gePC3DoiEaPap8tNHTYhzUYnBE7uad54fFkfDHm/WYkGSVZtvt5h0EGCWLJaQR78cU="
script:
- pytest
- sonar-scanner