language: python
addons:
  sonarcloud:
    organization: "slavaklevleev"
    token:
      secure: "Ttr7uXiInC2txCyPqG72vTFsAnOUYCwmH6isbAUEyVcFrol+fJVbu2qgsu8qoJf83daNAQSWAYYb+TBzvGLL7YfJKd2dJWUfuAJASEj/4SbOcF9L/Y6L0HPyyTb8gWYtN86K8Qp1MvZYD2iBjNI3VW7AOg5wrY5f6pGuwAaPstRch0oFBInN91U52N8YDofgXuMo7l6qkCZg2oaHnkKfW3Gvt97Iuwd3YgxFlkD8gCek0LUH/8P+k/UWKtBNEArZmHgWs8yLjhbyThe/F21+3HHLA9a9Oymp/W1wTbKbeQbiwyFhRaLqD9Wk1mMvyP9VEvR/VjnSVY+A7KjL4tFGXnXX55mGaphYz8KRzZzyD9k6Q4nz3RA/C2XDa5KkF4IhfQwEPDHTLx4jifdlPRSrsMy2/LBy7e4rrHnGsw0CCUKL2LUdPlb5Trq0hq+YKrVsXU2o1ngA9vBGqrZiUh2L2fpDqGMCr97XQ2MgXBQJdVWsOlhr48zgDP65McIWAzqOe7pPKs6QqZcU1Do2j9iqKlOLTRakiZHAYeLQdrLVfUrVm4VXxfS8e67YAgxv5igivAmbxX3TfhdSh5WX8Qaq/wBGfS90AHmFPjklUzOqyXOnf7LFuHOtG1u7FGE6F7I5Vt4MOl80gmvE78V9NkXyDQhyNkzTwkw1B/kYhOvRC5Y="
script:
- pytest
- sonar-scanner
env:
  global:
  - secure: "kp5ebtwj/CbG5dBBSBdfRvca7KrLNr0QrtalvYyMA4nPIavF5aBsr4HxYxhTks/bkVC5rS2EDPOxODfY0XghcUDPq3jtR9Xn64sJFriuPHTrzhwwHf2sXv5ZwshilBPvN5t3jPHXgE7ytA4h/Fb1iElKFVpBk8wQx1tSqsCeKmHVboQ1e/Movu1JJfrXdXNXANROUZb4TuSIDBrAf8KnltfanzY1i8z/8FfS9wnE6d9qjLteQKzelzEtyy+9e7XF1PwIp2jCjonsUfKUEVC8ut+n4zF1CQljHwTawpFgYv9q+2+JyVgdboJhR4cFG+rMPDJE8teS/74/khZhilZFBuPP2ayDL51+PwzpEaxkp5Aoimy+lRB54q3YBphNsKuWKBrKSwCBxTdP+9OKXTt/x5fotPye5ok9ETCW3YswYlbUrWJ6eMP3RyEyQmK2frkxXQaKSaZRdydM/XHDSbuGFpUP2EmTcKy+lap1irCnYlsER3qDsim0526Ow2caNYc+kFKyXovjVS8IGoG0besVfB9hyAHQgsrrSI3UbdlBR0QB5VLFg+J0k9QTOG5Web5sbv09dYjBUofXYhflVzEoAFcRIxpKVRszERqKzxwkV0QE1exI1L2OZAZ8OCrDtbZRgTfLxWFKL76tYgq93smy/YBj1ee+cDaa6XH/0EPTPqk="
